# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=300)),
                ('shortened_url', models.CharField(max_length=30)),
            ],
        ),
    ]
